const default_client_id = "chrome_120"
const default_headers = {
  accept: "*/*",
  "accept-encoding": "gzip, deflate, br",
  "accept-language": "en-US,en;q=0.9",
  "sec-ch-ua": `"Chromium";v="118", "Google Chrome";v="118", "Not=A?Brand";v="99"`,
  "sec-ch-ua-mobile": "?0",
  "sec-ch-ua-platform": '"Windows"',
  "sec-fetch-dest": "empty",
  "sec-fetch-mode": "cors",
  "sec-fetch-site": "same-origin",
  "sec-fetch-user": "?1",
  "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36",
}
const default_header_order = [
  "host",
  "x-real-ip",
  "x-forwarded-for",
  "connection",
  "content-length",
  "cache-control",
  "sec-ch-ua",
  "accept-datetime",
  "dnt",
  "x-csrf-token",
  "if-unmodified-since",
  "authorization",
  "x-requested-with",
  "if-modified-since",
  "max-forwards",
  "x-http-method-override",
  "x-request-id",
  "sec-ch-ua-platform",
  "pragma",
  "upgrade-insecure-requests",
  "sec-ch-ua-mobile",
  "user-agent",
  "content-type",
  "if-none-match",
  "if-match",
  "if-range",
  "range",
  "accept",
  "origin",
  "sec-fetch-site",
  "sec-fetch-mode",
  "sec-fetch-dest",
  "referer",
  "accept-encoding",
  "accept-language",
]

module.exports = {
  default_client_id,
  default_headers,
  default_header_order
}